import { CheckIcon, DownloadIcon, TriangleUpIcon } from '@chakra-ui/icons';
import { Box, SimpleGrid, Icon, Text, VStack, Flex, Center } from '@chakra-ui/react';
const Feature = ({ title, text, icon }) => {
    return (
        <VStack >
            <Flex
                w={16}
                h={16}
                align={'center'}
                justify={'center'}
                color={'tomato'}
                rounded={'full'}
                bg={'gray.100'}
                mb={1}>
                    {icon}
            </Flex>
            <Text fontWeight={600}>{title}</Text>
            <Text color={'gray.600'}>{text}</Text>
        </VStack>
    );
};

export default function Features() {
    return (
        <Box p={5} py={10}>
            <SimpleGrid columns={{ base: 1, md: 3 }} spacing={10}>
                <Feature
                    icon={<CheckIcon w={10} h={10} />}
                    title={'Workouts on demand'}
                    text={
                        'Access, Modify, and Store your workouts on Cloud. Use the Explore page to find free workouts generated by users.'
                    }
                />
                <Feature
                    icon={<TriangleUpIcon w={10} h={10} />}
                    title={'Intuitive Workout Builder'}
                    text={
                        'Use our very own Workout Builder to create the workout that works for you. With customizaibility at the forefront creativity for athletes and coaches are not limited.'
                    }
                />
                <Feature
                    icon={<DownloadIcon w={10} h={10} />}
                    title={'Workout Exportability'}
                    text={
                        'With our export functionality you\'ll find it easy to share your workouts to friends, clients, peers.'
                    }
                />
            </SimpleGrid>
        </Box>
    );
}
